### ISSUE TITLE
I don't understand how to send message after successful payment!!

### ISSUE THREAD

**Issue by romanrakhlin** [cxspxr/telegram-payments#1]
Please, help me

`
@bot.message_handler(content_types=['text'])	
   elif message.text == 'Заказать книгу (Русский)':
	    bot.send_invoice(message.chat.id, 
	    	title='Книга',
			description='"Твой Первый Миллион"',
			provider_token='410694247:TEST:9c670c7f-6557-4abc-b22d-b18fe63b18b2',
			currency='RUB',
			is_flexible=False,
			prices=[PRICE_RUB],
			start_parameter='test-payment',
			invoice_payload='Custom-Payload')

@bot.pre_checkout_query_handler(func=lambda query: True)
def process_pre_checkout_query(pre_checkout_query: types.PreCheckoutQuery):
    bot.answer_pre_checkout_query(pre_checkout_query.id, ok=True)

@bot.message_handler(content_types=['SUCCESSFUL_PAYMENT'])
def process_successful_payment(Message):
	bot.send_message(
        message.chat.id, 'successful_payment')`

And after pay I see this:
![Screen Shot 2019-07-20 at 22 23 08](https://user-images.githubusercontent.com/51785794/61583763-fba82900-ab3c-11e9-9616-59cb4e9ad90e.png)

massege don't send

**Comment by cxspxr-me** [comment]
Please, refer to original python-telegram-bot docs. This serves as my personal project. You can use success hook for custom message. Default success message is already displayed as I see.

**Comment by romanrakhlin** [comment]
he message is displayed, but you know how to check, was the payment made and only after that did the message appear? In my case, after payment, display the book files. I looked at the API of the telegram and still did not understand how to do it.

**Comment by cxspxr-me** [comment]
Look into python-telegram-bot git, not to the API docs directly. See e.g. 
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/paymentbot.py and successful callback method
